version: "3.7"

services:
  tp-angular:
    container_name: tp-angular
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "4201:4200"
