version: "3.5"
services:
  angular-pmn: # The name of the service
    container_name: tp-angular-pmn # Container name
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # Volume binding
      - ".:/usr/src/app"
    ports:
      - "4200:4200" # Port mapping
