version: "3.5" # We use version 3.5 syntax
services:
  angular-service:
    container_name: angular-docker-pmn # Container name
    build: ./ # Location of our Dockerfile
    volumes: # Volume binding
      - "./tp-angular-pmn:/usr/src/app"
    ports:
      - "4200:4200" # Port mapping
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
